"""Create finetuning jobs table

Revision ID: 4cdff6540ce2
Revises: 85d69ec0fcd3
Create Date: 2025-10-22 06:45:05.330168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdff6540ce2'
down_revision: Union[str, Sequence[str], None] = '85d69ec0fcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetuning_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('training_file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finetuning_jobs_agent_id'), 'finetuning_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_finetuning_jobs_status'), 'finetuning_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finetuning_jobs_status'), table_name='finetuning_jobs')
    op.drop_index(op.f('ix_finetuning_jobs_agent_id'), table_name='finetuning_jobs')
    op.drop_table('finetuning_jobs')
    # ### end Alembic commands ###
