"""Add weight_visualizations table

Revision ID: cf4bbfe59765
Revises: 4cdff6540ce2
Create Date: 2025-10-25 13:35:08.545719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf4bbfe59765'
down_revision: Union[str, Sequence[str], None] = '4cdff6540ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_visualizations',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('layers_data', mysql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['finetuning_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.drop_column('finetuning_jobs', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finetuning_jobs', sa.Column('model_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('weight_visualizations')
    # ### end Alembic commands ###
